use phf::{phf_map as map, phf_set as set, Map, Set};

pub static SYLLABARY: Map<&'static str, &'static str> = map! {
	"ke" => "ケ",
	"ryu" => "リュ",
	"be" => "ベ",
	"to" => "ト",
	"gya" => "ギャ",
	"po" => "ポ",
	"yu" => "ユ",
	"hyu" => "ヒュ",
	"byo" => "ビョ",
	"gyu" => "ギュ",
	"te" => "テ",
	"ko" => "コ",
	"tsu" => "ツ",
	"hi" => "ヒ",
	"we" => "ヱ",
	"re" => "レ",
	"na" => "ナ",
	"ha" => "ハ",
	"bi" => "ビ",
	"mya" => "ミャ",
	"no" => "ノ",
	"ya" => "ヤ",
	"ne" => "ネ",
	"sho" => "ショ",
	"ra" => "ラ",
	"dja" => "ヂャ",
	"dju" => "ヂュ",
	"fu" => "フ",
	"da" => "ダ",
	"wa" => "ワ",
	"i" => "イ",
	"do" => "ド",
	"so" => "ソ",
	"ryo" => "リョ",
	"ja" => "ジャ",
	"n" => "ン",
	"wi" => "ヰ",
	"gu" => "グ",
	"he" => "ヘ",
	"u" => "ウ",
	"zu" => "ズ",
	"ze" => "ゼ",
	"pyu" => "ピュ",
	"ga" => "ガ",
	"bo" => "ボ",
	"ku" => "ク",
	"myu" => "ミュ",
	"nya" => "ニャ",
	"myo" => "ミョ",
	"za" => "ザ",
	"ru" => "ル",
	"nyo" => "ニョ",
	"pi" => "ピ",
	"bya" => "ビャ",
	"cha" => "チャ",
	"mi" => "ミ",
	"ji" => "ジ",
	"ta" => "タ",
	"ju" => "ジュ",
	"yo" => "ヨ",
	"zo" => "ゾ",
	"kyo" => "キョ",
	"ni" => "ニ",
	"ro" => "ロ",
	"pa" => "パ",
	"ba" => "バ",
	"bu" => "ブ",
	"ho" => "ホ",
	"gyo" => "ギョ",
	"jo" => "ジョ",
	"ka" => "カ",
	"djo" => "ヂョ",
	"pya" => "ピャ",
	"chi" => "チ",
	"ma" => "マ",
	"dzu" => "ヅ",
	"gi" => "ギ",
	"pu" => "プ",
	"e" => "エ",
	"ge" => "ゲ",
	"mo" => "モ",
	"o" => "オ",
	"shi" => "シ",
	"shu" => "シュ",
	"chu" => "チュ",
	"hya" => "ヒャ",
	"me" => "メ",
	"rya" => "リャ",
	"kya" => "キャ",
	"de" => "デ",
	"wo" => "ヲ",
	"mu" => "ム",
	"a" => "ア",
	"sha" => "シャ",
	"ri" => "リ",
	"pyo" => "ピョ",
	"kyu" => "キュ",
	"su" => "ス",
	"ki" => "キ",
	"hyo" => "ヒョ",
	"sa" => "サ",
	"byu" => "ビュ",
	"se" => "セ",
	"nu" => "ヌ",
	"nyu" => "ニュ",
	"dji" => "ヂ",
	"go" => "ゴ",
	"cho" => "チョ",
	"pe" => "ペ",
};

pub static EXTENDED_SYLLABARY: Map<&'static str, &'static str> = map! {
	"yi" => "イィ",
	"ye" => "イェ",
	"wi" => "ウィ",
	"we" => "ウェ",
	"wo" => "ウォ",
	"va" => "ヴァ",
	"vi" => "ヴィ",
	"vu" => "ヴ",
	"ve" => "ヴェ",
	"vo" => "ヴォ",
	"vya" => "ヴャ",
	"vyu" => "ヴュ",
	"vye" => "ヴィェ",
	"vyo" => "ヴョ",
	"kye" => "キェ",
	"gye" => "ギェ",
	"kwa" => "クァ",
	"kwi" => "クィ",
	"kwe" => "クェ",
	"kwo" => "クォ",
	"gwa" => "グァ",
	"gwi" => "グィ",
	"gwe" => "グェ",
	"gwo" => "グォ",
	"she" => "シェ",
	"je" => "ジェ",
	"si" => "スィ",
	"zi" => "ズィ",
	"tsa" => "ツァ",
	"tsi" => "ツィ",
	"tse" => "ツェ",
	"tso" => "ツォ",
	"tsyu" => "ツュ",
	"ti" => "ティ",
	"tu" => "トゥ",
	"tyu" => "テュ",
	"di" => "ディ",
	"du" => "ドゥ",
	"dyu" => "デュ",
	"nye" => "ニェ",
	"hye" => "ヒェ",
	"bye" => "ビェ",
	"pye" => "ピェ",
	"fa" => "ファ",
	"fi" => "フィ",
	"fe" => "フェ",
	"fo" => "フォ",
	"fya" => "フャ",
	"fyu" => "フュ",
	"fye" => "フィェ",
	"fyo" => "フョ",
	"hu" => "ホゥ",
	"mye" => "ミェ",
	"rye" => "リェ",
	"la" => "ラ゜",
	"li" => "リ゜",
	"lu" => "ル゜",
	"le" => "レ゜",
	"lo" => "ロ゜",
	"lya" => "リ゜ャ",
	"lyu" => "リ゜ュ",
	"lye" => "リ゜ェ",
	"lyo" => "リ゜ョ",
};

pub const SOKUON_GRAPH: &'static str = "ッ";
pub static SOKUON_MATCHES: Set<&'static str> = set! {
	"kk",
	"cc",
	"dd",
	"gg",
	"pp",
	"ss",
	"tt",
};

pub const CHOONPU_GRAPH: &'static str = "ー";
pub static CHOONPU_MATCHES: Set<&'static str> = set! {
	"aa",
	"ii",
	"uu",
	"ee",
	"oo",
};
